export const FETCH_DOMAIN_NODES = 'FETCH_DOMAIN_NODES'

export const EMPTY_PAGE_NODES = 'EMPTY_PAGE_NODES'
export const EMPTY_EDGES = 'EMPTY_EDGES'

export const CONCAT_PAGE_NODES = 'CONCAT_PAGE_NODES'
export const CONCAT_EDGES = 'CONCAT_EDGES'

export const PUSH_PAGE_NODE = 'PUSH_PAGE_NODE'

export const SET_DRAGGING_TAG = 'SET_DRAGGING_TAG'
