export const SET_DOMAIN_NODE = 'SET_DOMAIN_NODE'

export const EMPTY_PAGE_NODES = 'EMPTY_PAGE_NODES'
export const EMPTY_EDGES = 'EMPTY_EDGES'

export const CONCAT_PAGE_NODES = 'CONCAT_PAGE_NODES'
export const CONCAT_EDGES = 'CONCAT_EDGES'

export const DELETE_PAGE_NODE = 'DELETE_PAGE_NODE'

export const PUSH_PAGE_NODE = 'PUSH_PAGE_NODE'
export const PUSH_COMPONENT_NODE = 'PUSH_COMPONENT_NODE'

export const SET_DRAGGING_TAG = 'SET_DRAGGING_TAG'

export const UPDATE_PAGE_NODE = 'UPDATE_PAGE_NODE'
